export const homePath = '/'
export const timesPath = '/times'
export const currentTimesPath = '/current'
export const loginFormPath = '/login'
export const submitWaitingTimeFormPath = '/submit-waiting-time'
